### ISSUE TITLE
missing neginf in utils.py

### ISSUE THREAD

**Issue by meiyoufeng116** [jokieleung/NTRD#2]
when I run the code by _python run.py_, it says:
```
Traceback (most recent call last):
  File "e2e_run.py", line 36, in <module>
    from e2e_model import E2ECrossModel
  File "/home/NTRD/e2e_model.py", line 1, in <module>
    from models.transformer import TorchGeneratorModel,_build_encoder,_build_decoder,_build_encoder_mask, _build_encoder4kg, _build_decoder4kg, _build_decoder_selection, _build_decoder_e2e_selection
  File "/home/NTRD/models/transformer.py", line 15, in <module>
    from models.utils import neginf
ImportError: cannot import name 'neginf'
```

And I can't find the **neginf** in the utils.py. Is the code aviliable now?

**Comment by meiyoufeng116** [comment]
the neginf function has been found in KGSF's /model/utils.py, and I recommend that before running the code, put all code in  KGSF's /model/utils.py into utils.py.

**Comment by jokieleung** [comment]
Thx for your feedback. Problem solved.
